/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controle;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadastrarFuncionario extends javax.swing.JFrame {

    Controle controle;
    
    public CadastrarFuncionario(Controle c) {
        initComponents();
        this.controle = c;
        JP_setorGerente.setVisible(false);
        JP_nivel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_nivel = new javax.swing.ButtonGroup();
        JP_dadosFuncionario = new javax.swing.JPanel();
        JL_nome = new javax.swing.JLabel();
        JL_cpf = new javax.swing.JLabel();
        JL_salario = new javax.swing.JLabel();
        JTF_nome = new javax.swing.JTextField();
        JFT_cpf = new javax.swing.JFormattedTextField();
        JFT_salario = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        JCB_cargo = new javax.swing.JComboBox<>();
        JP_nivel = new javax.swing.JPanel();
        JL_nivel = new javax.swing.JLabel();
        JRB_jr = new javax.swing.JRadioButton();
        JRB_pleno = new javax.swing.JRadioButton();
        JRB_senior = new javax.swing.JRadioButton();
        JP_setorGerente = new javax.swing.JPanel();
        JCB_setorBox = new javax.swing.JComboBox<>();
        JL_setor = new javax.swing.JLabel();
        JP_botoes = new javax.swing.JPanel();
        JB_adicionar = new javax.swing.JButton();
        JB_limpar = new javax.swing.JButton();
        JB_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JP_dadosFuncionario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadastro de Funcionário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        JL_nome.setText("Nome:");

        JL_cpf.setText("CPF:");

        JL_salario.setText("Salário:");

        try {
            JFT_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JFT_salario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        JFT_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFT_salarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Cargo:");

        JCB_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Vendedor", "Gerente" }));
        JCB_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_cargoActionPerformed(evt);
            }
        });

        JL_nivel.setText("Nível:");

        BG_nivel.add(JRB_jr);
        JRB_jr.setSelected(true);
        JRB_jr.setText("Junior");
        JRB_jr.setContentAreaFilled(false);
        JRB_jr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JRB_jr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_jrActionPerformed(evt);
            }
        });

        BG_nivel.add(JRB_pleno);
        JRB_pleno.setText("Pleno");
        JRB_pleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_plenoActionPerformed(evt);
            }
        });

        BG_nivel.add(JRB_senior);
        JRB_senior.setText("Senior");

        javax.swing.GroupLayout JP_nivelLayout = new javax.swing.GroupLayout(JP_nivel);
        JP_nivel.setLayout(JP_nivelLayout);
        JP_nivelLayout.setHorizontalGroup(
            JP_nivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_nivelLayout.createSequentialGroup()
                .addComponent(JL_nivel)
                .addGap(18, 18, 18)
                .addComponent(JRB_jr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRB_pleno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRB_senior)
                .addGap(102, 102, 102))
        );

        JP_nivelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JRB_jr, JRB_pleno, JRB_senior});

        JP_nivelLayout.setVerticalGroup(
            JP_nivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_nivelLayout.createSequentialGroup()
                .addGroup(JP_nivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_nivel)
                    .addComponent(JRB_jr)
                    .addComponent(JRB_pleno)
                    .addComponent(JRB_senior))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        JCB_setorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comercial", "Marketing", "Cobrança", "Recursos Humanos" }));

        JL_setor.setText("Setor:");

        javax.swing.GroupLayout JP_setorGerenteLayout = new javax.swing.GroupLayout(JP_setorGerente);
        JP_setorGerente.setLayout(JP_setorGerenteLayout);
        JP_setorGerenteLayout.setHorizontalGroup(
            JP_setorGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_setorGerenteLayout.createSequentialGroup()
                .addComponent(JL_setor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(JCB_setorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        JP_setorGerenteLayout.setVerticalGroup(
            JP_setorGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_setorGerenteLayout.createSequentialGroup()
                .addGroup(JP_setorGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_setorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_setor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JP_dadosFuncionarioLayout = new javax.swing.GroupLayout(JP_dadosFuncionario);
        JP_dadosFuncionario.setLayout(JP_dadosFuncionarioLayout);
        JP_dadosFuncionarioLayout.setHorizontalGroup(
            JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_dadosFuncionarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JP_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JP_dadosFuncionarioLayout.createSequentialGroup()
                            .addGroup(JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JL_nome)
                                .addComponent(JL_cpf)
                                .addComponent(JL_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JFT_salario, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                .addComponent(JTF_nome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JFT_cpf, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(JP_dadosFuncionarioLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(JCB_cargo, 0, 241, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_dadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JP_setorGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JP_dadosFuncionarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JCB_cargo, JFT_cpf, JFT_salario, JTF_nome});

        JP_dadosFuncionarioLayout.setVerticalGroup(
            JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_dadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_cpf)
                    .addComponent(JFT_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_salario)
                    .addComponent(JFT_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_dadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JP_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JP_setorGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        JB_adicionar.setText("Adicionar");
        JB_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_adicionarActionPerformed(evt);
            }
        });

        JB_limpar.setText("Limpar");
        JB_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_limparActionPerformed(evt);
            }
        });

        JB_sair.setText("Sair");
        JB_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_botoesLayout = new javax.swing.GroupLayout(JP_botoes);
        JP_botoes.setLayout(JP_botoesLayout);
        JP_botoesLayout.setHorizontalGroup(
            JP_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_botoesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JB_adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JP_botoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JB_adicionar, JB_limpar, JB_sair});

        JP_botoesLayout.setVerticalGroup(
            JP_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_botoesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(JP_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_sair)
                    .addComponent(JB_limpar)
                    .addComponent(JB_adicionar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JP_botoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_dadosFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JP_dadosFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JP_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFT_salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFT_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFT_salarioActionPerformed

    private void JCB_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_cargoActionPerformed
        if (JCB_cargo.getSelectedIndex() == 2) {
            JP_setorGerente.setVisible(true);
            JP_nivel.setVisible(false);
        } else if (JCB_cargo.getSelectedIndex() == 1) {
            JP_nivel.setVisible(true);
            JP_setorGerente.setVisible(false);
        } else {
            JP_setorGerente.setVisible(false);
            JP_nivel.setVisible(false);
        }
        
    }//GEN-LAST:event_JCB_cargoActionPerformed

    private void JB_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_limparActionPerformed
        this.limpar();
    }//GEN-LAST:event_JB_limparActionPerformed

    private void JB_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_JB_sairActionPerformed

    private void JB_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_adicionarActionPerformed
        String nome = this.JTF_nome.getText();
        String cpf = this.JFT_cpf.getText();
        String aux = this.JFT_salario.getText();
        NumberFormat formatador = NumberFormat.getInstance(new Locale("pt", "BR"));
        
        try {
            Number salario = formatador.parse(aux);
            if (JCB_cargo.getSelectedIndex() == 0) {
                controle.cadastrarFuncionario(nome, cpf, salario.doubleValue());
            } else if(JCB_cargo.getSelectedIndex() == 2) {
                controle.cadastrarGerente(nome, cpf, salario.doubleValue(), JCB_setorBox.getSelectedItem().toString());
            } else {
                String nivel = JRB_jr.isSelected() ? "Junior" : JRB_pleno.isSelected() ? "Pleno" : "Senior";
                controle.cadastrarVendedor(nome, cpf, salario.doubleValue(), nivel);
            }

                JOptionPane.showMessageDialog(rootPane, "Funcionário cadastrado com sucesso!", "Cadastro de Funcionário", WIDTH);

        } catch (ParseException ex) {
            Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.limpar();
    }//GEN-LAST:event_JB_adicionarActionPerformed

    private void JRB_jrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_jrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_jrActionPerformed

    private void JRB_plenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_plenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_plenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG_nivel;
    private javax.swing.JButton JB_adicionar;
    private javax.swing.JButton JB_limpar;
    private javax.swing.JButton JB_sair;
    private javax.swing.JComboBox<String> JCB_cargo;
    private javax.swing.JComboBox<String> JCB_setorBox;
    private javax.swing.JFormattedTextField JFT_cpf;
    private javax.swing.JFormattedTextField JFT_salario;
    private javax.swing.JLabel JL_cpf;
    private javax.swing.JLabel JL_nivel;
    private javax.swing.JLabel JL_nome;
    private javax.swing.JLabel JL_salario;
    private javax.swing.JLabel JL_setor;
    private javax.swing.JPanel JP_botoes;
    private javax.swing.JPanel JP_dadosFuncionario;
    private javax.swing.JPanel JP_nivel;
    private javax.swing.JPanel JP_setorGerente;
    private javax.swing.JRadioButton JRB_jr;
    private javax.swing.JRadioButton JRB_pleno;
    private javax.swing.JRadioButton JRB_senior;
    private javax.swing.JTextField JTF_nome;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        this.JTF_nome.setText(null);
        this.JFT_cpf.setText(null);
        this.JFT_salario.setText(null);
        this.JCB_cargo.setSelectedIndex(0);
    }
    
}
