/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControleCliente;
import java.util.ArrayList;

/**
 *
 * @author Aluno
 */
public class RelatorioCliente extends javax.swing.JDialog {

    /**
     * Creates new form RelatorioCliente
     */
    ControleCliente controleCliente;
    public RelatorioCliente(java.awt.Frame parent, boolean modal, ControleCliente controleCliente) {
        super(parent, modal);
        initComponents();
        this.controleCliente = controleCliente;
        this.mudarVisibilidadeItensPesquisa(false);
        this.JCB_listaClientes.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JRG_tipoRelatorio = new javax.swing.ButtonGroup();
        JP_relatorio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_relatorio = new javax.swing.JTextArea();
        JP_opcoesRelatorio = new javax.swing.JPanel();
        JL_tipoRelatorio = new javax.swing.JLabel();
        JRB_todosClientes = new javax.swing.JRadioButton();
        JRB_umCliente = new javax.swing.JRadioButton();
        JL_pesquisa = new javax.swing.JLabel();
        JTF_pesquisa = new javax.swing.JTextField();
        JB_pesquisar = new javax.swing.JButton();
        JCB_listaClientes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JTA_relatorio.setEditable(false);
        JTA_relatorio.setColumns(20);
        JTA_relatorio.setRows(5);
        jScrollPane1.setViewportView(JTA_relatorio);

        javax.swing.GroupLayout JP_relatorioLayout = new javax.swing.GroupLayout(JP_relatorio);
        JP_relatorio.setLayout(JP_relatorioLayout);
        JP_relatorioLayout.setHorizontalGroup(
            JP_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_relatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        JP_relatorioLayout.setVerticalGroup(
            JP_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_relatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        JL_tipoRelatorio.setText("Tipo de relatório:");

        JRG_tipoRelatorio.add(JRB_todosClientes);
        JRB_todosClientes.setText("Todos os clientes");
        JRB_todosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_todosClientesActionPerformed(evt);
            }
        });

        JRG_tipoRelatorio.add(JRB_umCliente);
        JRB_umCliente.setText("Um cliente");
        JRB_umCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_umClienteActionPerformed(evt);
            }
        });

        JL_pesquisa.setText("Pesquisa:");

        JB_pesquisar.setText("Pesquisar");
        JB_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_pesquisarActionPerformed(evt);
            }
        });

        JCB_listaClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCB_listaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_listaClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_opcoesRelatorioLayout = new javax.swing.GroupLayout(JP_opcoesRelatorio);
        JP_opcoesRelatorio.setLayout(JP_opcoesRelatorioLayout);
        JP_opcoesRelatorioLayout.setHorizontalGroup(
            JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JL_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JL_tipoRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                        .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                                .addComponent(JRB_todosClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JRB_umCliente))
                            .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                                .addComponent(JTF_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(JB_pesquisar)))
                        .addGap(38, 38, 38))
                    .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                        .addComponent(JCB_listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JP_opcoesRelatorioLayout.setVerticalGroup(
            JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_tipoRelatorio)
                    .addComponent(JRB_todosClientes)
                    .addComponent(JRB_umCliente))
                .addGap(18, 18, 18)
                .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_pesquisa)
                    .addComponent(JTF_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(JCB_listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JP_opcoesRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP_opcoesRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(JP_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRB_todosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_todosClientesActionPerformed
        // TODO add your handling code here:
        this.mudarVisibilidadeItensPesquisa(false);
        this.JTA_relatorio.setText(controleCliente.getRelatorioTodosClientes());
    }//GEN-LAST:event_JRB_todosClientesActionPerformed

    private void JRB_umClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_umClienteActionPerformed
        // TODO add your handling code here:
        this.JTA_relatorio.setText(null);
        this.mudarVisibilidadeItensPesquisa(true);
    }//GEN-LAST:event_JRB_umClienteActionPerformed

    private void JB_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_pesquisarActionPerformed
        // TODO add your handling code here:
        String chave = this.JTF_pesquisa.getText();
        if(controleCliente.ehCliente(chave)){
            this.JTA_relatorio.setText(controleCliente.getRelatorioUmCliente(this.JTF_pesquisa.getText()));
        }else{
            ArrayList<String> listaClientes = controleCliente.getClientes(chave);
            if(listaClientes.size() > 0){
                JCB_listaClientes.setVisible(true);
                String[] ar = listaClientes.toArray(new String[0]);
                JCB_listaClientes.setModel(new javax.swing.DefaultComboBoxModel<>(ar));
                JCB_listaClientes.setSelectedIndex(-1);
            }else{
                JTA_relatorio.setText("Cliente não localizado");
                JCB_listaClientes.setVisible(false);
            }
        }
        this.JTF_pesquisa.setText(null);
        
        
    }//GEN-LAST:event_JB_pesquisarActionPerformed

    private void JCB_listaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_listaClientesActionPerformed
        // TODO add your handling code here:
        String chave = JCB_listaClientes.getSelectedItem().toString().split(" - ")[0];
        this.JTA_relatorio.setText(controleCliente.getRelatorioUmCliente(chave));
    }//GEN-LAST:event_JCB_listaClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioCliente dialog = new RelatorioCliente(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void mudarVisibilidadeItensPesquisa(boolean b){
        this.JL_pesquisa.setVisible(b);
        this.JTF_pesquisa.setVisible(b);
        this.JB_pesquisar.setVisible(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_pesquisar;
    private javax.swing.JComboBox<String> JCB_listaClientes;
    private javax.swing.JLabel JL_pesquisa;
    private javax.swing.JLabel JL_tipoRelatorio;
    private javax.swing.JPanel JP_opcoesRelatorio;
    private javax.swing.JPanel JP_relatorio;
    private javax.swing.JRadioButton JRB_todosClientes;
    private javax.swing.JRadioButton JRB_umCliente;
    private javax.swing.ButtonGroup JRG_tipoRelatorio;
    private javax.swing.JTextArea JTA_relatorio;
    private javax.swing.JTextField JTF_pesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
