/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleCliente;
import controller.ControleFuncionario;

public class TelaPrincipal extends javax.swing.JFrame {

    ControleFuncionario controleFuncionario = new ControleFuncionario();
    ControleCliente controleCliente = new ControleCliente();
    
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.JP_relatorioFuncionario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_relatorioFuncionario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_relatorioFuncionarios = new javax.swing.JTextArea();
        JL_funcionarios = new javax.swing.JLabel();
        JCB_funcionarios = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_opcoes = new javax.swing.JMenu();
        JMI_sair = new javax.swing.JMenuItem();
        JM_funcionario = new javax.swing.JMenu();
        JMI_cadastrar = new javax.swing.JMenuItem();
        JMI_emitirRelatorio = new javax.swing.JMenuItem();
        JM_cliente = new javax.swing.JMenu();
        JMI_cadastrarCliente = new javax.swing.JMenuItem();
        JMI_emitirRelatorioCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTA_relatorioFuncionarios.setEditable(false);
        JTA_relatorioFuncionarios.setColumns(20);
        JTA_relatorioFuncionarios.setRows(5);
        jScrollPane1.setViewportView(JTA_relatorioFuncionarios);

        JL_funcionarios.setText("Funcionário: ");

        JCB_funcionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        JCB_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_funcionariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_relatorioFuncionarioLayout = new javax.swing.GroupLayout(JP_relatorioFuncionario);
        JP_relatorioFuncionario.setLayout(JP_relatorioFuncionarioLayout);
        JP_relatorioFuncionarioLayout.setHorizontalGroup(
            JP_relatorioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_relatorioFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_funcionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JCB_funcionarios, 0, 307, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(JP_relatorioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JP_relatorioFuncionarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        JP_relatorioFuncionarioLayout.setVerticalGroup(
            JP_relatorioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_relatorioFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_relatorioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_funcionarios)
                    .addComponent(JCB_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(335, Short.MAX_VALUE))
            .addGroup(JP_relatorioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JP_relatorioFuncionarioLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        JM_opcoes.setText("Opções");

        JMI_sair.setText("Sair");
        JMI_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_sairActionPerformed(evt);
            }
        });
        JM_opcoes.add(JMI_sair);

        jMenuBar1.add(JM_opcoes);

        JM_funcionario.setText("Funcionário");
        JM_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_funcionarioActionPerformed(evt);
            }
        });

        JMI_cadastrar.setText("Cadastrar");
        JMI_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_cadastrarActionPerformed(evt);
            }
        });
        JM_funcionario.add(JMI_cadastrar);

        JMI_emitirRelatorio.setText("Emitir Relatório");
        JMI_emitirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_emitirRelatorioActionPerformed(evt);
            }
        });
        JM_funcionario.add(JMI_emitirRelatorio);

        jMenuBar1.add(JM_funcionario);

        JM_cliente.setText("Cliente");
        JM_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_clienteActionPerformed(evt);
            }
        });

        JMI_cadastrarCliente.setText("Cadastrar");
        JMI_cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_cadastrarClienteActionPerformed(evt);
            }
        });
        JM_cliente.add(JMI_cadastrarCliente);

        JMI_emitirRelatorioCliente.setText("Emitir Relatório");
        JMI_emitirRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_emitirRelatorioClienteActionPerformed(evt);
            }
        });
        JM_cliente.add(JMI_emitirRelatorioCliente);

        jMenuBar1.add(JM_cliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_relatorioFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_relatorioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMI_sairActionPerformed

    private void JMI_emitirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_emitirRelatorioActionPerformed
        this.JTA_relatorioFuncionarios.setText(controleFuncionario.getRelatorioTodosFuncionarios());
        this.JP_relatorioFuncionario.setVisible(true);
        JCB_funcionarios.setModel(new javax.swing.DefaultComboBoxModel<>(controleFuncionario.getCpfFuncionarios()));
    }//GEN-LAST:event_JMI_emitirRelatorioActionPerformed

    private void JMI_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_cadastrarActionPerformed
        new CadastrarFuncionario(this.controleFuncionario).setVisible(true);
    }//GEN-LAST:event_JMI_cadastrarActionPerformed

    private void JM_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JM_funcionarioActionPerformed

    private void JCB_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_funcionariosActionPerformed
       if (JCB_funcionarios.getSelectedIndex() > 0) {
            String cpfSelecionado = JCB_funcionarios.getSelectedItem().toString();
            cpfSelecionado = cpfSelecionado.split(" - ")[0];
            String relatorio = controleFuncionario.getRelatorioFuncionario(cpfSelecionado);
            JTA_relatorioFuncionarios.setText(relatorio);
       } else {
            JTA_relatorioFuncionarios.setText(controleFuncionario.getRelatorioTodosFuncionarios());
       }
    }//GEN-LAST:event_JCB_funcionariosActionPerformed

    private void JM_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_clienteActionPerformed
        
    }//GEN-LAST:event_JM_clienteActionPerformed

    private void JMI_cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_cadastrarClienteActionPerformed
       new CadastroCliente(this, rootPaneCheckingEnabled, controleCliente).setVisible(true);
    }//GEN-LAST:event_JMI_cadastrarClienteActionPerformed

    private void JMI_emitirRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_emitirRelatorioClienteActionPerformed
        // TODO add your handling code here:
        new RelatorioCliente(this, rootPaneCheckingEnabled, controleCliente).setVisible(true);
    }//GEN-LAST:event_JMI_emitirRelatorioClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCB_funcionarios;
    private javax.swing.JLabel JL_funcionarios;
    private javax.swing.JMenuItem JMI_cadastrar;
    private javax.swing.JMenuItem JMI_cadastrarCliente;
    private javax.swing.JMenuItem JMI_emitirRelatorio;
    private javax.swing.JMenuItem JMI_emitirRelatorioCliente;
    private javax.swing.JMenuItem JMI_sair;
    private javax.swing.JMenu JM_cliente;
    private javax.swing.JMenu JM_funcionario;
    private javax.swing.JMenu JM_opcoes;
    private javax.swing.JPanel JP_relatorioFuncionario;
    private javax.swing.JTextArea JTA_relatorioFuncionarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
