//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Conta.java
//  @ Date : 15/03/2024
//  @ Author : 
//
//



import java.text.DecimalFormat;
public class Conta {
	public String numeroAgencia;
	public String numeroConta;
	public String nomeTitular;
	public double saldo;
	public double limite;

	DecimalFormat df = new DecimalFormat("###.##");

	public boolean transferir(double valor, Conta destino) {
		if (this.sacar(valor)) {
			destino.depositar(valor);
			return true;
		}
		return false;
	}
	
	public void depositar(double valor) {
		this.saldo += valor;
	}
	
	public boolean sacar(double valor) {
		if (this.saldo >= valor * 1.005) {
			this.saldo -= valor * 1.005;
			return true;
		}
		return false;
	}
	
	public boolean investir(double valor, String tipo) {
		if (this.sacar(valor)) return true;
		return false;
	}

	
	public String getRelatorio() {
		String s = "\nAgencia: "+ this.numeroAgencia;
		s += "\nConta: "+ this.numeroConta;
		s += "\nTitular: "+ this.nomeTitular; 
		s += "\nSaldo: R$ "+ String.format(".2f", this.saldo)  + "\n";
		return s;
	}
}
