/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controle;

/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Controle controle = new Controle();
    
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_relatorioFuncionarios = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_opcoes = new javax.swing.JMenu();
        JMI_sair = new javax.swing.JMenuItem();
        JM_funcionario = new javax.swing.JMenu();
        JMI_cadastrar = new javax.swing.JMenuItem();
        JMI_emitirRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTA_relatorioFuncionarios.setColumns(20);
        JTA_relatorioFuncionarios.setRows(5);
        jScrollPane1.setViewportView(JTA_relatorioFuncionarios);

        JM_opcoes.setText("Opções");

        JMI_sair.setText("Sair");
        JMI_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_sairActionPerformed(evt);
            }
        });
        JM_opcoes.add(JMI_sair);

        jMenuBar1.add(JM_opcoes);

        JM_funcionario.setText("Funcionário");

        JMI_cadastrar.setText("Cadastrar");
        JMI_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_cadastrarActionPerformed(evt);
            }
        });
        JM_funcionario.add(JMI_cadastrar);

        JMI_emitirRelatorio.setText("Emitir Relatório");
        JMI_emitirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_emitirRelatorioActionPerformed(evt);
            }
        });
        JM_funcionario.add(JMI_emitirRelatorio);

        jMenuBar1.add(JM_funcionario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMI_sairActionPerformed

    private void JMI_emitirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_emitirRelatorioActionPerformed
        this.JTA_relatorioFuncionarios.setText(controle.getRelatorioFuncionarios());
    }//GEN-LAST:event_JMI_emitirRelatorioActionPerformed

    private void JMI_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_cadastrarActionPerformed
        new CadastrarFuncionario(this.controle).setVisible(true);
    }//GEN-LAST:event_JMI_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMI_cadastrar;
    private javax.swing.JMenuItem JMI_emitirRelatorio;
    private javax.swing.JMenuItem JMI_sair;
    private javax.swing.JMenu JM_funcionario;
    private javax.swing.JMenu JM_opcoes;
    private javax.swing.JTextArea JTA_relatorioFuncionarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
